name: Run Data Historica Por Hora

on:
  schedule:
    - cron: "0 12 * * *"  # Cada día a las 12:00 UTC
  workflow_dispatch:      # Para ejecutarlo manualmente

jobs:
  bachero:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACTION }}
          fetch-depth: 0 
          ref: main

      # 2. Configurar usuario de Git
      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      # 3. Sincronizar la rama main antes de ejecutar el notebook
      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      # 4. Configurar Miniconda e instalar dependencias
      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      # 5. Ejecutar el notebook de datos históricos
      - name: Instalar dependencias y ejecutar notebook
        shell: bash -l {0}
        run: |
          conda install -y pip papermill ipykernel pandas numpy scikit-learn yfinance
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill downloadDataHistYF.ipynb /dev/null -k python3
      
      - name: subir cambios al repo
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main

  pm40:
    needs: bachero
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GIT_ACTION }}
            fetch-depth: 0
            ref: main

      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Install depedencias y Ejecutar Promedio Movil
        shell: bash -l {0}
        run: |
          conda install -y papermill ipykernel pandas numpy scikit-learn yfinance ta-lib
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill PM40_PromedioMovil40.ipynb /dev/null -k python3

      - name: subir cambios al repositorio
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook PM40" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main

  RupCanalResistencia:
    needs: bachero
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACTION }}
          fetch-depth: 0
          ref: main

      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Instalar dependencias y ejecutar notebook Ruptura canal
        shell: bash -l {0}
        run: |
          conda install -y pip papermill ipykernel pandas numpy scikit-learn yfinance
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill BreakOut_Indicator.ipynb /dev/null -k python3
        
      - name: subir cambios al repo
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook Rup. Canal Resistencia" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main

  cncf:
    needs: bachero
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GIT_ACTION }}
            fetch-depth: 0
            ref: main

      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Install depedencias y Ejecutar Promedio Movil
        shell: bash -l {0}
        run: |
          conda install -y papermill ipykernel pandas numpy scikit-learn yfinance ta-lib
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill CNCF_CaidaNormalCaidaFuerte.ipynb /dev/null -k python3

      - name: subir cambios al repositorio
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook CNCF" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main

  gapAlza:
    needs: bachero
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GIT_ACTION }}
            fetch-depth: 0
            ref: main

      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Install depedencias y Ejecutar Promedio Movil
        shell: bash -l {0}
        run: |
          conda install -y papermill ipykernel pandas numpy scikit-learn yfinance ta-lib
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill PrimerGapAlza.ipynb /dev/null -k python3

      - name: subir cambios al repositorio
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook Primer Gap a la Alza" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main

  pisoFuerte:
    needs: bachero
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GIT_ACTION }}
            fetch-depth: 0
            ref: main
      
      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Install depedencias y Ejecutar Piso Fuerte
        shell: bash -l {0}
        run: |
          conda install -y papermill ipykernel pandas numpy scikit-learn yfinance ta-lib
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill pisoFuerte.ipynb /dev/null -k python3

      - name: subir cambios al repositorio
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook Piso Fuerte" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main

  breakOut_Alcista:
    needs: bachero
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GIT_ACTION }}
            fetch-depth: 0
            ref: main

      - name: Configurar usuario de Git
        run: |
          git config user.email "kaliinversionesyservicios@gmail.com"
          git config user.name "kaliinversionesyservicios"

      - name: Sincronizar rama main (pull --rebase)
        run: |
          git pull --rebase origin main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: myenv
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Install depedencias y Ejecutar BreakOut_Acista
        shell: bash -l {0}
        run: |
          conda install -y papermill ipykernel pandas numpy scikit-learn yfinance ta-lib
          pip install backtesting
          python -m ipykernel install --user --name python3
          papermill BreakOut_alcista.ipynb /dev/null -k python3

      - name: subir cambios al repositorio
        shell: bash -l {0}
        env:
          TOKEN: ${{ secrets.GIT_ACTION }}
        run: |
          git add .
          git commit -m "Update data notebook BreakOut_Acista" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main




